logging:
  level:
    grid:
      bit: debug
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        data: TRACE
        data.jpa: TRACE
        jdbc:
          core:
            PreparedStatementCreator: TRACE
            StatementCreatorUtils: TRACE
    sql: debug

spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://192.168.99.100:5432/dev
  flyway:
    enabled: false
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false